### ISSUE TITLE
Min/max scale is hard coded

### ISSUE THREAD

**Issue by ivptr** [irons163/IRSticker-swift#1]
It would be nice to be able to alter these values during the initialization:

```
let kStickerMinScale: CGFloat = 0.5
let kStickerMaxScale: CGFloat = 2.0
```

**Comment by irons163** [comment]
I'll consider about this.

**Comment by ivptr** [comment]
Actually, I think there should be no limits in place as default.

**Comment by irons163** [comment]
Please update to version 0.2.0.

**Comment by ivptr** [comment]
Many thanks!

How about to disable limits completely when set stickerMinScale and stickerMaxScale to 0?

**Comment by irons163** [comment]
Sounds not bad. I'll try it and check the results. Perhaps you can help me for check by setting stickerMinScale with a very small value. I think one of the biggest problems would be if the images become too small, it would hard to tap and the control buttons would fold with each other.

**Comment by ivptr** [comment]
I've already tried commenting out that part of the code. 

When it is extremely small it is still possible to tap delete control, which is the most important thing.

**Comment by irons163** [comment]
Yes, the delete control button is on the top of others, confirmed.  I'm going to release this new feature.
